package entity;
// Generated Jan 19, 2017 1:02:32 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Attendencie generated by hbm2java
 */
@Entity
@Table(name="attendencie"
    ,catalog="festivali"
)
public class Attendencie  implements java.io.Serializable {


     private AttendencieId id = new AttendencieId();
     private Festival festival;
     private Date startTime;
     private Date endTime;

    public Attendencie() {
    }

	
    public Attendencie(AttendencieId id, Festival festival) {
        this.id = id;
        this.festival = festival;
    }
    public Attendencie(AttendencieId id, Festival festival, Date startTime, Date endTime) {
       this.id = id;
       this.festival = festival;
       this.startTime = startTime;
       this.endTime = endTime;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idFestival", column=@Column(name="IdFestival", nullable=false) ), 
        @AttributeOverride(name="performer", column=@Column(name="Performer", nullable=false, length=45) ) } )
    public AttendencieId getId() {
        return this.id;
    }
    
    public void setId(AttendencieId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IdFestival", nullable=false, insertable=false, updatable=false)
    public Festival getFestival() {
        return this.festival;
    }
    
    public void setFestival(Festival festival) {
        this.festival = festival;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="StartTime", length=19)
    public Date getStartTime() {
        return this.startTime;
    }
    
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="EndTime", length=19)
    public Date getEndTime() {
        return this.endTime;
    }
    
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }




}


