package entity;
// Generated Jan 19, 2017 1:02:32 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AttendencieId generated by hbm2java
 */
@Embeddable
public class AttendencieId  implements java.io.Serializable {


     private int idFestival;
     private String performer;

    public AttendencieId() {
    }

    public AttendencieId(int idFestival, String performer) {
       this.idFestival = idFestival;
       this.performer = performer;
    }
   


    @Column(name="IdFestival", nullable=false)
    public int getIdFestival() {
        return this.idFestival;
    }
    
    public void setIdFestival(int idFestival) {
        this.idFestival = idFestival;
    }


    @Column(name="Performer", nullable=false, length=45)
    public String getPerformer() {
        return this.performer;
    }
    
    public void setPerformer(String performer) {
        this.performer = performer;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AttendencieId) ) return false;
		 AttendencieId castOther = ( AttendencieId ) other; 
         
		 return (this.getIdFestival()==castOther.getIdFestival())
 && ( (this.getPerformer()==castOther.getPerformer()) || ( this.getPerformer()!=null && castOther.getPerformer()!=null && this.getPerformer().equals(castOther.getPerformer()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdFestival();
         result = 37 * result + ( getPerformer() == null ? 0 : this.getPerformer().hashCode() );
         return result;
   }   


}


