package entity;
// Generated Jan 19, 2017 1:02:32 PM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Link generated by hbm2java
 */
@Entity
@Table(name="link"
    ,catalog="festivali"
)
public class Link  implements java.io.Serializable {


     private LinkId id = new LinkId();
     private Festival festival;
     private String link;

    public Link() {
    }

	
    public Link(LinkId id, Festival festival) {
        this.id = id;
        this.festival = festival;
    }
    public Link(LinkId id, Festival festival, String link) {
       this.id = id;
       this.festival = festival;
       this.link = link;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idFestival", column=@Column(name="IdFestival", nullable=false) ), 
        @AttributeOverride(name="name", column=@Column(name="Name", nullable=false, length=45) ) } )
    public LinkId getId() {
        return this.id;
    }
    
    public void setId(LinkId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IdFestival", nullable=false, insertable=false, updatable=false)
    public Festival getFestival() {
        return this.festival;
    }
    
    public void setFestival(Festival festival) {
        this.festival = festival;
    }

    
    @Column(name="Link", length=45)
    public String getLink() {
        return this.link;
    }
    
    public void setLink(String link) {
        this.link = link;
    }




}


