package entity;
// Generated Jan 19, 2017 1:02:32 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Media generated by hbm2java
 */
@Entity
@Table(name="media"
    ,catalog="festivali"
)
public class Media  implements java.io.Serializable {


     private Integer idMedia;
     private Festival festival;
     private byte[] file;

    public Media() {
    }

    public Media(Festival festival, byte[] file) {
       this.festival = festival;
       this.file = file;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="IdMedia", unique=true, nullable=false)
    public Integer getIdMedia() {
        return this.idMedia;
    }
    
    public void setIdMedia(Integer idMedia) {
        this.idMedia = idMedia;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IdFestival")
    public Festival getFestival() {
        return this.festival;
    }
    
    public void setFestival(Festival festival) {
        this.festival = festival;
    }

    
    @Column(name="File")
    public byte[] getFile() {
        return this.file;
    }
    
    public void setFile(byte[] file) {
        this.file = file;
    }

}


