package entity;
// Generated Jan 19, 2017 1:02:32 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ReviewId generated by hbm2java
 */
@Embeddable
public class ReviewId  implements java.io.Serializable {


     private int idUser;
     private int idReservation;

    public ReviewId() {
    }

    public ReviewId(int idUser, int idReservation) {
       this.idUser = idUser;
       this.idReservation = idReservation;
    }
   


    @Column(name="IdUser", nullable=false)
    public int getIdUser() {
        return this.idUser;
    }
    
    public void setIdUser(int idUser) {
        this.idUser = idUser;
    }


    @Column(name="IdReservation", nullable=false)
    public int getIdReservation() {
        return this.idReservation;
    }
    
    public void setIdReservation(int idReservation) {
        this.idReservation = idReservation;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ReviewId) ) return false;
		 ReviewId castOther = ( ReviewId ) other; 
         
		 return (this.getIdUser()==castOther.getIdUser())
 && (this.getIdReservation()==castOther.getIdReservation());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdUser();
         result = 37 * result + this.getIdReservation();
         return result;
   }   


}


