package entity;
// Generated Jan 19, 2017 1:02:32 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name="user"
    ,catalog="festivali"
    , uniqueConstraints = @UniqueConstraint(columnNames="Username") 
)
public class User  implements java.io.Serializable {


     private Integer idUser;
     private String username;
     private String email;
     private String password;
     private String name;
     private String surname;
     private String phone;
     private Integer approved;
     private Integer blocked;
     private Integer lives;
     private Date lastLogin;
     private String adminMessage;
     private Set<Reservation> reservations = new HashSet<Reservation>(0);

    public User() {
    }

	
    public User(String username, String email, String password, String name, String surname, String phone) {
        this.username = username;
        this.email = email;
        this.password = password;
        this.name = name;
        this.surname = surname;
        this.phone = phone;
    }
    public User(String username, String email, String password, String name, String surname, String phone, Integer approved, Integer blocked, Integer lives, Date lastLogin, String adminMessage, Set<Reservation> reservations) {
       this.username = username;
       this.email = email;
       this.password = password;
       this.name = name;
       this.surname = surname;
       this.phone = phone;
       this.approved = approved;
       this.blocked = blocked;
       this.lives = lives;
       this.lastLogin = lastLogin;
       this.adminMessage = adminMessage;
       this.reservations = reservations;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="IdUser", unique=true, nullable=false)
    public Integer getIdUser() {
        return this.idUser;
    }
    
    public void setIdUser(Integer idUser) {
        this.idUser = idUser;
    }

    
    @Column(name="Username", unique=true, nullable=false, length=45)
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }

    
    @Column(name="Email", nullable=false, length=45)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="Password", nullable=false, length=45)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    
    @Column(name="Name", nullable=false, length=45)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="Surname", nullable=false, length=45)
    public String getSurname() {
        return this.surname;
    }
    
    public void setSurname(String surname) {
        this.surname = surname;
    }

    
    @Column(name="Phone", nullable=false, length=45)
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }

    
    @Column(name="Approved")
    public Integer getApproved() {
        return this.approved;
    }
    
    public void setApproved(Integer approved) {
        this.approved = approved;
    }

    
    @Column(name="Blocked")
    public Integer getBlocked() {
        return this.blocked;
    }
    
    public void setBlocked(Integer blocked) {
        this.blocked = blocked;
    }

    
    @Column(name="Lives")
    public Integer getLives() {
        return this.lives;
    }
    
    public void setLives(Integer lives) {
        this.lives = lives;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="LastLogin", length=19)
    public Date getLastLogin() {
        return this.lastLogin;
    }
    
    public void setLastLogin(Date lastLogin) {
        this.lastLogin = lastLogin;
    }

    
    @Column(name="AdminMessage", length=160)
    public String getAdminMessage() {
        return this.adminMessage;
    }
    
    public void setAdminMessage(String adminMessage) {
        this.adminMessage = adminMessage;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="user")
    public Set<Reservation> getReservations() {
        return this.reservations;
    }
    
    public void setReservations(Set<Reservation> reservations) {
        this.reservations = reservations;
    }




}


